"""some fixes

Revision ID: 0c15d41c3e3a
Revises: 671fbcb0e61c
Create Date: 2025-04-08 18:56:30.706539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c15d41c3e3a'
down_revision: Union[str, None] = '671fbcb0e61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tasks', 'cron',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tasks', 'command',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'command',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tasks', 'cron',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tasks', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
